// Generated by CoffeeScript 1.7.1
var array, nextnum, num, total, _i, _j, _len;

array = [1, 2];

total = 0;

for (num = _i = 1; _i <= 30; num = ++_i) {
  nextnum = array[array.length - 2] + array[array.length - 1];
  if (nextnum > 4000000) {
    break;
  } else {
    array.push(nextnum);
  }
}

for (_j = 0, _len = array.length; _j < _len; _j++) {
  num = array[_j];
  if (num % 2 === 0) {
    total += num;
  } else {
    null;
  }
}

console.log(array);

console.log(array.length);

console.log("total: " + total);
